version: '3'

services:
  node-js-server:
    container_name: node-js-server
    build:
      context: ./
      dockerfile: Dockerfile-node-js-server
    working_dir: /usr/capstone-1/app
    tty: true
    command: tail -F anything
    volumes:
      - ./capstone-1:/usr/capstone-1
    ports:
      - "3001:3001"

  # ganachecli: simulated test rpc on dev environment
  ganache-cli:
    container_name: ganache-cli
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug

  # truffle-suite
  truffle-drizzle:
    container_name: truffle-drizzle
    working_dir: /capstone-1
    build:
      context: ./
      dockerfile: Dockerfile-truffle-drizzle
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8545
      interval: 5s
      timeout: 5s
      retries: 5
    command: tail -F anything
#    If desired you can automate truffle commands on start-up!
#    command: >
#      sh -c "truffle compile &&
#             truffle test &&
#             truffle migrate &&
#             cp -R output/contracts client/src/contracts/ &&
#             cd client &&
#             npm start"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./capstone-1:/capstone-1
